=== uo293873/sew-2025/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchura, fecha, horaInicio, numeroVueltas, localidad, pais, patrocinadorPrincipal, 
    referencias, fotos, videos, coordenadasOrigen, tramos, vencedor, clasificacionMundial)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidades CDATA #REQUIRED>

<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidades CDATA #REQUIRED>

<!ELEMENT fecha (#PCDATA)>

<!ELEMENT horaInicio (#PCDATA)>

<!ELEMENT numeroVueltas (#PCDATA)>

<!ELEMENT localidad (#PCDATA)>

<!ELEMENT pais (#PCDATA)>

<!ELEMENT patrocinadorPrincipal (#PCDATA)>

<!ELEMENT referencias (referencia, referencia, referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotos (foto+)>
<!ELEMENT foto (#PCDATA)>

<!ELEMENT videos (video+)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT coordenadasOrigen (longitudGeo, latitudGeo, altitudGeo)>
<!ELEMENT longitudGeo (#PCDATA)>
<!ELEMENT latitudGeo (#PCDATA)>
<!ELEMENT altitudGeo (#PCDATA)>

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, coordenadas, sector)>

<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>

<!ELEMENT coordenadas (longitudGeo, latitudGeo, altitudGeo)>

<!ELEMENT sector (#PCDATA)>

<!ELEMENT vencedor (nombrePiloto, tiempoCarrera)>
<!ELEMENT nombrePiloto (#PCDATA)>
<!ELEMENT tiempoCarrera (#PCDATA)>

<!ELEMENT clasificacionMundial (pilotoClasificado, pilotoClasificado, pilotoClasificado)>
<!ELEMENT pilotoClasificado (nombrePilotoClasificado, puntosPiloto)>
<!ATTLIST pilotoClasificado posicion CDATA #REQUIRED>
<!ELEMENT nombrePilotoClasificado (#PCDATA)>
<!ELEMENT puntosPiloto (#PCDATA)>

=== uo293873/sew-2025/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>Petronas Sepang International Circuit</nombre>
    
    <longitud unidades="metros">5540</longitud>
    
    <anchura unidades="metros">16</anchura>
    
    <fecha>2025-10-26</fecha>
    
    <horaInicio>8:00</horaInicio>
    
    <numeroVueltas>20</numeroVueltas>
    
    <localidad>Sepang</localidad>
    
    <pais>Malasia</pais>
    
    <patrocinadorPrincipal>Petronas</patrocinadorPrincipal>
    
    <referencias>
        <referencia>https://www.motogp.com/es/calendar/2025/event/malaysia/c2cd8f49-5643-440f-84fc-4c37b3ef3f87?tab=circuit-info</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Sepang</referencia>
        <referencia>https://www.sepangcircuit.com/</referencia>
    </referencias>
    
    <fotos>
        <foto>multimedia/sepang_panorama.jpg</foto>
        <foto>multimedia/recta.jpg</foto>
        <foto>multimedia/tramos.jpg</foto>
    </fotos>
    
    <videos>
        <video>multimedia/track_lap_sepang.mp4</video>
    </videos>
    
    <coordenadasOrigen>
        <longitudGeo>101.7383756</longitudGeo>
        <latitudGeo>2.7607531</latitudGeo>
        <altitudGeo>35.98</altitudGeo>
    </coordenadasOrigen>
    
    <tramos>
        <tramo>
            <distancia unidades="metros">616.79</distancia>
            <coordenadas>
                <longitudGeo>101.7328390</longitudGeo>
                <latitudGeo>2.7603226</latitudGeo>
                <altitudGeo>37.90</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">29.37</distancia>
            <coordenadas>
                <longitudGeo>101.7326400</longitudGeo>
                <latitudGeo>2.7604965</latitudGeo>
                <altitudGeo>37.64</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">26.49</distancia>
            <coordenadas>
                <longitudGeo>101.7326180</longitudGeo>
                <latitudGeo>2.7607337</latitudGeo>
                <altitudGeo>37.51</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">34.52</distancia>
            <coordenadas>
                <longitudGeo>101.7328290</longitudGeo>
                <latitudGeo>2.7609616</latitudGeo>
                <altitudGeo>37.12</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">64.89</distancia>
            <coordenadas>
                <longitudGeo>101.7333978</longitudGeo>
                <latitudGeo>2.7608282</latitudGeo>
                <altitudGeo>35.64</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">23.19</distancia>
            <coordenadas>
                <longitudGeo>101.7335728</longitudGeo>
                <latitudGeo>2.7609420</latitudGeo>
                <altitudGeo>35.17</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">29.22</distancia>
            <coordenadas>
                <longitudGeo>101.7335513</longitudGeo>
                <latitudGeo>2.7612039</latitudGeo>
                <altitudGeo>34.20</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">58.25</distancia>
            <coordenadas>
                <longitudGeo>101.7332334</longitudGeo>
                <latitudGeo>2.7616205</latitudGeo>
                <altitudGeo>31.23</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">68.33</distancia>
            <coordenadas>
                <longitudGeo>101.7330698</longitudGeo>
                <latitudGeo>2.7622129</latitudGeo>
                <altitudGeo>27.53</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">95.71</distancia>
            <coordenadas>
                <longitudGeo>101.7332008</longitudGeo>
                <latitudGeo>2.7630636</latitudGeo>
                <altitudGeo>23.51</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">70.22</distancia>
            <coordenadas>
                <longitudGeo>101.7335642</longitudGeo>
                <latitudGeo>2.7635804</latitudGeo>
                <altitudGeo>22.58</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">58.73</distancia>
            <coordenadas>
                <longitudGeo>101.7340156</longitudGeo>
                <latitudGeo>2.7638555</latitudGeo>
                <altitudGeo>22.57</altitudGeo>
            </coordenadas>
            <sector>1</sector>
        </tramo>

        <tramo>
            <distancia unidades="metros">193.33</distancia>
            <coordenadas>
                <longitudGeo>101.7356666</longitudGeo>
                <latitudGeo>2.7644064</latitudGeo>
                <altitudGeo>36.67</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">217.58</distancia>
            <coordenadas>
                <longitudGeo>101.7374712</longitudGeo>
                <latitudGeo>2.7651679</latitudGeo>
                <altitudGeo>36.57</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">23.23</distancia>
            <coordenadas>
                <longitudGeo>101.7376351</longitudGeo>
                <latitudGeo>2.7650381</latitudGeo>
                <altitudGeo>37.29</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">241.5</distancia>
            <coordenadas>
                <longitudGeo>101.7380690</longitudGeo>
                <latitudGeo>2.7629099</latitudGeo>
                <altitudGeo>39.97</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">50.04</distancia>
            <coordenadas>
                <longitudGeo>101.7383169</longitudGeo>
                <latitudGeo>2.7625341</latitudGeo>
                <altitudGeo>37.85</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">78.9</distancia>
            <coordenadas>
                <longitudGeo>101.7389548</longitudGeo>
                <latitudGeo>2.7622218</latitudGeo>
                <altitudGeo>36.32</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">61.96</distancia>
            <coordenadas>
                <longitudGeo>101.7395095</longitudGeo>
                <latitudGeo>2.7622808</latitudGeo>
                <altitudGeo>36.46</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">84.97</distancia>
            <coordenadas>
                <longitudGeo>101.7400830</longitudGeo>
                <latitudGeo>2.7627866</latitudGeo>
                <altitudGeo>37.80</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">67.3</distancia>
            <coordenadas>
                <longitudGeo>101.7406477</longitudGeo>
                <latitudGeo>2.7630061</latitudGeo>
                <altitudGeo>38.68</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">70.02</distancia>
            <coordenadas>
                <longitudGeo>101.7412354</longitudGeo>
                <latitudGeo>2.7627781</latitudGeo>
                <altitudGeo>38.62</altitudGeo>
            </coordenadas>
            <sector>2</sector>
        </tramo>

        <tramo>
            <distancia unidades="metros">309.5</distancia>
            <coordenadas>
                <longitudGeo>101.7430443</longitudGeo>
                <latitudGeo>2.7606608</latitudGeo>
                <altitudGeo>38.81</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">110.6</distancia>
            <coordenadas>
                <longitudGeo>101.7426547</longitudGeo>
                <latitudGeo>2.7597454</latitudGeo>
                <altitudGeo>38.00</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">477.25</distancia>
            <coordenadas>
                <longitudGeo>101.7383839</longitudGeo>
                <latitudGeo>2.7592718</latitudGeo>
                <altitudGeo>34.04</altitudGeo>
            </coordenadas>
            <sector>3</sector>
        </tramo>
        <tramo>
            <distancia unidades="metros">19.27</distancia>
            <coordenadas>
                <longitudGeo>101.7383406</longitudGeo>
